# Generated by Django 5.0.6 on 2025-10-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
